language: python
python:
  - "3.5.2"
# command to install dependencies
install:
  - "pip install pylint"
  - "pip install coveralls"
# command to run tests
script:
  - nosetests -v --with-coverage
  - "python pylint_runner.py"
after_success:
- coveralls